"""Public API for the time-series analysis skill package."""

from skill_time_series_analysis.analysis import (
    TimeSeriesAnalyzer,
    analysis_results_to_df,
    analyze_pair_cointegration,
    analyze_price_series,
    analyze_spread,
    analyze_time_series,
    analyze_time_series_yearly,
    cointegration_diagnostics,
    distribution_diagnostics,
    engle_granger_cointegration,
    ensure_dir_and_get_path,
    half_life_of_mean_reversion,
    kde_analysis,
    mean_reversion_diagnostics,
    qq_analysis,
    stationarity_diagnostics,
    ts_analysis,
    ts_groupby_period,
)
from skill_time_series_analysis.factors import (
    build_time_series_factor_frame,
    ts_mean_reversion_zscore,
    ts_momentum,
    ts_trend_slope,
    ts_volatility,
)
from skill_time_series_analysis.types import (
    CointegrationAnalysis,
    DistributionDiagnostics,
    MeanReversionAnalysis,
    TimeSeriesAnalysis,
)

__all__ = [
    "CointegrationAnalysis",
    "DistributionDiagnostics",
    "MeanReversionAnalysis",
    "TimeSeriesAnalysis",
    "TimeSeriesAnalyzer",
    "analysis_results_to_df",
    "analyze_pair_cointegration",
    "analyze_price_series",
    "analyze_spread",
    "analyze_time_series",
    "analyze_time_series_yearly",
    "build_time_series_factor_frame",
    "cointegration_diagnostics",
    "distribution_diagnostics",
    "engle_granger_cointegration",
    "ensure_dir_and_get_path",
    "half_life_of_mean_reversion",
    "kde_analysis",
    "mean_reversion_diagnostics",
    "qq_analysis",
    "stationarity_diagnostics",
    "ts_analysis",
    "ts_groupby_period",
    "ts_mean_reversion_zscore",
    "ts_momentum",
    "ts_trend_slope",
    "ts_volatility",
]
