"""Public API for the time-series analysis skill package."""

from skill_time_series_analysis.analysis import (
    TimeSeriesAnalyzer,
    analysis_results_to_df,
    analyze_pair_cointegration,
    analyze_price_series,
    analyze_spread,
    analyze_time_series,
    analyze_time_series_yearly,
    cointegration_diagnostics,
    distribution_diagnostics,
    engle_granger_cointegration,
    ensure_dir_and_get_path,
    half_life_of_mean_reversion,
    kde_analysis,
    log_diff_diagnostics,
    mean_reversion_diagnostics,
    qq_analysis,
    stationarity_diagnostics,
    ts_analysis,
    ts_groupby_period,
)
from skill_time_series_analysis.reporting import (
    generate_pair_cointegration_report,
    generate_spread_report,
    generate_time_series_report,
    interpret_time_series_analysis,
)
from skill_time_series_analysis.types import (
    AnalysisReport,
    CointegrationAnalysis,
    DistributionDiagnostics,
    MeanReversionAnalysis,
    TimeSeriesAnalysis,
    TimeSeriesInterpretation,
    TimeSeriesReport,
)

__all__ = [
    "CointegrationAnalysis",
    "DistributionDiagnostics",
    "MeanReversionAnalysis",
    "TimeSeriesAnalysis",
    "TimeSeriesInterpretation",
    "TimeSeriesReport",
    "TimeSeriesAnalyzer",
    "AnalysisReport",
    "analysis_results_to_df",
    "analyze_pair_cointegration",
    "analyze_price_series",
    "analyze_spread",
    "analyze_time_series",
    "analyze_time_series_yearly",
    "cointegration_diagnostics",
    "distribution_diagnostics",
    "engle_granger_cointegration",
    "generate_pair_cointegration_report",
    "generate_spread_report",
    "generate_time_series_report",
    "ensure_dir_and_get_path",
    "half_life_of_mean_reversion",
    "interpret_time_series_analysis",
    "kde_analysis",
    "log_diff_diagnostics",
    "mean_reversion_diagnostics",
    "qq_analysis",
    "stationarity_diagnostics",
    "ts_analysis",
    "ts_groupby_period",
]
